export const CryptoData = [
    {
        percentage:9.10,
        month:2,
        amounts:25,
    },
    {
        percentage:9.10,
        month:4,
        amounts:35,
    },
    {
        percentage:8.50,
        month:5,
        amounts:55,
    },
    {
        percentage:8.20,
        month:6,
        amounts:95,
    },
    {
        percentage:7.50,
        month:8,
        amounts:55,
    },
    {
        percentage:7.35,
        month:9,
        amounts:45,
    },
    {
        percentage:7.10,
        month:11,
        amounts:75,
    },
    {
        percentage:6.90,
        month:12,
        amounts:65,
    },
    {
        percentage:6.50,
        month:12,
        amounts:75,
    },
];

